remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Welcome to the BertoCisneros homepage
description: Feel free to give an A on this assignment and any other projects it contains
